version: '3.8'

services:
  nginx: 
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    environment:
      - name=value
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
  
  mariadb:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    # ports:
    #   - "3306:3306"
    environment:
        MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
        USER: ${USER}
        MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: /home/ychalant/data/wordpress
  db:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: /home/ychalant/data/mariadb

networks:
  inception:
    driver: bridge

